// Code generated by protoc-gen-go. DO NOT EDIT.
// source: general.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	general.proto
	logger_messages.proto
	logger_service.proto
	registry_messages.proto
	registry_service.proto

It has these top-level messages:
	Health
	Empty
	Severity
	LogEntry
	Constraint
	ConstraintedLogRequest
	LoggerResponse
	SignedServiceInfo
	LogEntriesCount
	ServiceType
	ServiceTypesList
	RegistryResponse
	Service
	ServiceList
	ServiceInfo
	InstanceInfo
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Health struct {
	Up bool `protobuf:"varint,1,opt,name=up" json:"up,omitempty"`
}

func (m *Health) Reset()                    { *m = Health{} }
func (m *Health) String() string            { return proto1.CompactTextString(m) }
func (*Health) ProtoMessage()               {}
func (*Health) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Health) GetUp() bool {
	if m != nil {
		return m.Up
	}
	return false
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto1.RegisterType((*Health)(nil), "proto.Health")
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
}

func init() { proto1.RegisterFile("general.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 83 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4f, 0xcd, 0x4b,
	0x2d, 0x4a, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x12, 0x5c,
	0x6c, 0x1e, 0xa9, 0x89, 0x39, 0x25, 0x19, 0x42, 0x7c, 0x5c, 0x4c, 0xa5, 0x05, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x1c, 0x41, 0x4c, 0xa5, 0x05, 0x4a, 0xec, 0x5c, 0xac, 0xae, 0xb9, 0x05, 0x25, 0x95,
	0x49, 0x6c, 0x60, 0x95, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x0b, 0x13, 0x82, 0x41,
	0x00, 0x00, 0x00,
}
