// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	messages.proto
	registry_service.proto

It has these top-level messages:
	Empty
	ServiceType
	ServiceTypesList
	RegistryResponse
	Service
	ServiceList
	ServiceInfo
	InstanceInfo
	Health
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type RegistryResponse_Code int32

const (
	RegistryResponse___DEFAULT       RegistryResponse_Code = 0
	RegistryResponse_OK              RegistryResponse_Code = 1
	RegistryResponse_INVALID         RegistryResponse_Code = 2
	RegistryResponse_FAIL            RegistryResponse_Code = 3
	RegistryResponse_CANCELED        RegistryResponse_Code = 4
	RegistryResponse_NOT_IMPLEMENTED RegistryResponse_Code = 5
	RegistryResponse_NULL            RegistryResponse_Code = 6
	RegistryResponse_EXISTS          RegistryResponse_Code = 7
)

var RegistryResponse_Code_name = map[int32]string{
	0: "__DEFAULT",
	1: "OK",
	2: "INVALID",
	3: "FAIL",
	4: "CANCELED",
	5: "NOT_IMPLEMENTED",
	6: "NULL",
	7: "EXISTS",
}
var RegistryResponse_Code_value = map[string]int32{
	"__DEFAULT":       0,
	"OK":              1,
	"INVALID":         2,
	"FAIL":            3,
	"CANCELED":        4,
	"NOT_IMPLEMENTED": 5,
	"NULL":            6,
	"EXISTS":          7,
}

func (x RegistryResponse_Code) String() string {
	return proto1.EnumName(RegistryResponse_Code_name, int32(x))
}
func (RegistryResponse_Code) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ServiceType struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *ServiceType) Reset()                    { *m = ServiceType{} }
func (m *ServiceType) String() string            { return proto1.CompactTextString(m) }
func (*ServiceType) ProtoMessage()               {}
func (*ServiceType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServiceType) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type ServiceTypesList struct {
	Types []*ServiceType `protobuf:"bytes,1,rep,name=types" json:"types,omitempty"`
}

func (m *ServiceTypesList) Reset()                    { *m = ServiceTypesList{} }
func (m *ServiceTypesList) String() string            { return proto1.CompactTextString(m) }
func (*ServiceTypesList) ProtoMessage()               {}
func (*ServiceTypesList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServiceTypesList) GetTypes() []*ServiceType {
	if m != nil {
		return m.Types
	}
	return nil
}

// RegistryResponse represents response from Registry service
// It contains status code and optional message
type RegistryResponse struct {
	Status  RegistryResponse_Code `protobuf:"varint,1,opt,name=status,enum=proto.RegistryResponse_Code" json:"status,omitempty"`
	Message string                `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *RegistryResponse) Reset()                    { *m = RegistryResponse{} }
func (m *RegistryResponse) String() string            { return proto1.CompactTextString(m) }
func (*RegistryResponse) ProtoMessage()               {}
func (*RegistryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RegistryResponse) GetStatus() RegistryResponse_Code {
	if m != nil {
		return m.Status
	}
	return RegistryResponse___DEFAULT
}

func (m *RegistryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Service struct {
	Proto     string   `protobuf:"bytes,1,opt,name=proto" json:"proto,omitempty"`
	Type      string   `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Host      string   `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	Port      int32    `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	HttpPort  int32    `protobuf:"varint,5,opt,name=httpPort" json:"httpPort,omitempty"`
	Routes    []string `protobuf:"bytes,6,rep,name=routes" json:"routes,omitempty"`
	Health    string   `protobuf:"bytes,7,opt,name=health" json:"health,omitempty"`
	Weight    int32    `protobuf:"varint,8,opt,name=weight" json:"weight,omitempty"`
	Signature string   `protobuf:"bytes,9,opt,name=signature" json:"signature,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto1.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Service) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *Service) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Service) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Service) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Service) GetHttpPort() int32 {
	if m != nil {
		return m.HttpPort
	}
	return 0
}

func (m *Service) GetRoutes() []string {
	if m != nil {
		return m.Routes
	}
	return nil
}

func (m *Service) GetHealth() string {
	if m != nil {
		return m.Health
	}
	return ""
}

func (m *Service) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Service) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type ServiceList struct {
	Services []*Service `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
}

func (m *ServiceList) Reset()                    { *m = ServiceList{} }
func (m *ServiceList) String() string            { return proto1.CompactTextString(m) }
func (*ServiceList) ProtoMessage()               {}
func (*ServiceList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ServiceList) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type ServiceInfo struct {
	Type  string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Index int32  `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
}

func (m *ServiceInfo) Reset()                    { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string            { return proto1.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()               {}
func (*ServiceInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ServiceInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ServiceInfo) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type InstanceInfo struct {
	InstanceName string `protobuf:"bytes,1,opt,name=instanceName" json:"instanceName,omitempty"`
}

func (m *InstanceInfo) Reset()                    { *m = InstanceInfo{} }
func (m *InstanceInfo) String() string            { return proto1.CompactTextString(m) }
func (*InstanceInfo) ProtoMessage()               {}
func (*InstanceInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *InstanceInfo) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

type Health struct {
	Up bool `protobuf:"varint,1,opt,name=up" json:"up,omitempty"`
}

func (m *Health) Reset()                    { *m = Health{} }
func (m *Health) String() string            { return proto1.CompactTextString(m) }
func (*Health) ProtoMessage()               {}
func (*Health) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Health) GetUp() bool {
	if m != nil {
		return m.Up
	}
	return false
}

func init() {
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
	proto1.RegisterType((*ServiceType)(nil), "proto.ServiceType")
	proto1.RegisterType((*ServiceTypesList)(nil), "proto.ServiceTypesList")
	proto1.RegisterType((*RegistryResponse)(nil), "proto.RegistryResponse")
	proto1.RegisterType((*Service)(nil), "proto.Service")
	proto1.RegisterType((*ServiceList)(nil), "proto.ServiceList")
	proto1.RegisterType((*ServiceInfo)(nil), "proto.ServiceInfo")
	proto1.RegisterType((*InstanceInfo)(nil), "proto.InstanceInfo")
	proto1.RegisterType((*Health)(nil), "proto.Health")
	proto1.RegisterEnum("proto.RegistryResponse_Code", RegistryResponse_Code_name, RegistryResponse_Code_value)
}

func init() { proto1.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x25, 0x69, 0x3e, 0x67, 0x4b, 0xb1, 0x0c, 0x42, 0x16, 0xda, 0x43, 0xf1, 0x29, 0xe2, 0xd0,
	0x43, 0x41, 0x42, 0x48, 0x5c, 0xaa, 0x36, 0x2b, 0x22, 0xb2, 0xd9, 0x95, 0x9b, 0x45, 0xdc, 0xaa,
	0xc0, 0x9a, 0x26, 0x12, 0x4d, 0xa2, 0xd8, 0x01, 0xfa, 0x33, 0xf9, 0x01, 0xfc, 0x17, 0x64, 0xc7,
	0xcd, 0xee, 0x22, 0x4e, 0x99, 0xf7, 0xfc, 0xe6, 0xc5, 0xf3, 0xc6, 0x30, 0x3b, 0x70, 0x21, 0x8a,
	0x3d, 0x17, 0x8b, 0xb6, 0x6b, 0x64, 0x83, 0x5d, 0xfd, 0xa1, 0x3e, 0xb8, 0xf1, 0xa1, 0x95, 0x47,
	0xfa, 0x12, 0xce, 0xb6, 0xbc, 0xfb, 0x51, 0x7d, 0xe5, 0xf9, 0xb1, 0xe5, 0x18, 0x83, 0x23, 0x8f,
	0x2d, 0x27, 0xd6, 0xdc, 0x8a, 0x42, 0xa6, 0x6b, 0xfa, 0x1e, 0xd0, 0x3d, 0x89, 0x48, 0x2b, 0x21,
	0x71, 0x04, 0xae, 0x3a, 0x13, 0xc4, 0x9a, 0x4f, 0xa2, 0xb3, 0x25, 0x1e, 0xdc, 0x17, 0xf7, 0x74,
	0x6c, 0x10, 0xd0, 0xdf, 0x16, 0x20, 0xc6, 0xf7, 0x95, 0x90, 0xdd, 0x91, 0x71, 0xd1, 0x36, 0xb5,
	0xe0, 0xf8, 0x0d, 0x78, 0x42, 0x16, 0xb2, 0x17, 0xfa, 0x47, 0xb3, 0xe5, 0xb9, 0xe9, 0xff, 0x57,
	0xb8, 0x58, 0x37, 0xb7, 0x9c, 0x19, 0x2d, 0x26, 0xe0, 0x9b, 0x69, 0x88, 0xad, 0xef, 0x77, 0x82,
	0xf4, 0x00, 0x8e, 0x52, 0xe2, 0xc7, 0x10, 0xee, 0x76, 0x9b, 0xf8, 0x62, 0x75, 0x93, 0xe6, 0xe8,
	0x11, 0xf6, 0xc0, 0xbe, 0xfa, 0x88, 0x2c, 0x7c, 0x06, 0x7e, 0x92, 0x7d, 0x5a, 0xa5, 0xc9, 0x06,
	0xd9, 0x38, 0x00, 0xe7, 0x62, 0x95, 0xa4, 0x68, 0x82, 0xa7, 0x10, 0xac, 0x57, 0xd9, 0x3a, 0x4e,
	0xe3, 0x0d, 0x72, 0xf0, 0x53, 0x78, 0x92, 0x5d, 0xe5, 0xbb, 0xe4, 0xf2, 0x3a, 0x8d, 0x2f, 0xe3,
	0x2c, 0x8f, 0x37, 0xc8, 0x55, 0xe2, 0xec, 0x26, 0x4d, 0x91, 0x87, 0x01, 0xbc, 0xf8, 0x73, 0xb2,
	0xcd, 0xb7, 0xc8, 0xa7, 0x7f, 0x2c, 0xf0, 0xcd, 0xa8, 0xf8, 0x19, 0x0c, 0x91, 0x9a, 0xc8, 0x06,
	0x30, 0xe6, 0x68, 0xdf, 0xe5, 0xa8, 0xb8, 0xb2, 0x11, 0x92, 0x4c, 0x06, 0x4e, 0xd5, 0x8a, 0x6b,
	0x9b, 0x4e, 0x12, 0x67, 0x6e, 0x45, 0x2e, 0xd3, 0x35, 0x7e, 0x01, 0x41, 0x29, 0x65, 0x7b, 0xad,
	0x78, 0x57, 0xf3, 0x23, 0xc6, 0xcf, 0xc1, 0xeb, 0x9a, 0x5e, 0x72, 0x41, 0xbc, 0xf9, 0x24, 0x0a,
	0x99, 0x41, 0x8a, 0x2f, 0x79, 0xf1, 0x5d, 0x96, 0xc4, 0xd7, 0xee, 0x06, 0x29, 0xfe, 0x27, 0xaf,
	0xf6, 0xa5, 0x24, 0x81, 0x76, 0x32, 0x08, 0x9f, 0x43, 0x28, 0xaa, 0x7d, 0x5d, 0xc8, 0xbe, 0xe3,
	0x24, 0xd4, 0x2d, 0x77, 0x04, 0x7d, 0x37, 0x3e, 0x0a, 0xbd, 0xec, 0x57, 0x10, 0x88, 0x01, 0x9e,
	0xf6, 0x3d, 0x7b, 0xb8, 0x6f, 0x36, 0x9e, 0xd3, 0xb7, 0x63, 0x6b, 0x52, 0x7f, 0x6b, 0xfe, 0xf7,
	0x9e, 0x54, 0x62, 0x55, 0x7d, 0xcb, 0x7f, 0xe9, 0x70, 0x5c, 0x36, 0x00, 0xba, 0x84, 0x69, 0x52,
	0x0b, 0x59, 0xd4, 0xa6, 0x93, 0xc2, 0xb4, 0x32, 0x38, 0x2b, 0x0e, 0x27, 0x87, 0x07, 0x1c, 0x25,
	0xe0, 0x7d, 0x18, 0xe6, 0x9c, 0x81, 0xdd, 0xb7, 0x5a, 0x13, 0x30, 0xbb, 0x6f, 0xbf, 0x78, 0xfa,
	0x7e, 0xaf, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xa3, 0x6e, 0xdf, 0xff, 0x02, 0x00, 0x00,
}
