// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	messages.proto
	registry_service.proto

It has these top-level messages:
	Empty
	ServiceType
	ServiceTypesList
	RegistryResponse
	Service
	ServiceList
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type RegistryResponse_Code int32

const (
	RegistryResponse_OK              RegistryResponse_Code = 0
	RegistryResponse_INVALID         RegistryResponse_Code = 1
	RegistryResponse_FAIL            RegistryResponse_Code = 2
	RegistryResponse_CANCELED        RegistryResponse_Code = 3
	RegistryResponse_NOT_IMPLEMENTED RegistryResponse_Code = 4
	RegistryResponse_NULL            RegistryResponse_Code = 5
	RegistryResponse_EXISTS          RegistryResponse_Code = 6
)

var RegistryResponse_Code_name = map[int32]string{
	0: "OK",
	1: "INVALID",
	2: "FAIL",
	3: "CANCELED",
	4: "NOT_IMPLEMENTED",
	5: "NULL",
	6: "EXISTS",
}
var RegistryResponse_Code_value = map[string]int32{
	"OK":              0,
	"INVALID":         1,
	"FAIL":            2,
	"CANCELED":        3,
	"NOT_IMPLEMENTED": 4,
	"NULL":            5,
	"EXISTS":          6,
}

func (x RegistryResponse_Code) String() string {
	return proto1.EnumName(RegistryResponse_Code_name, int32(x))
}
func (RegistryResponse_Code) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ServiceType struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *ServiceType) Reset()                    { *m = ServiceType{} }
func (m *ServiceType) String() string            { return proto1.CompactTextString(m) }
func (*ServiceType) ProtoMessage()               {}
func (*ServiceType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServiceType) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type ServiceTypesList struct {
	Types []*ServiceType `protobuf:"bytes,1,rep,name=types" json:"types,omitempty"`
}

func (m *ServiceTypesList) Reset()                    { *m = ServiceTypesList{} }
func (m *ServiceTypesList) String() string            { return proto1.CompactTextString(m) }
func (*ServiceTypesList) ProtoMessage()               {}
func (*ServiceTypesList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServiceTypesList) GetTypes() []*ServiceType {
	if m != nil {
		return m.Types
	}
	return nil
}

// RegistryResponse represents response from Registry service
// It contains status code and optional message
type RegistryResponse struct {
	Status  RegistryResponse_Code `protobuf:"varint,1,opt,name=status,enum=proto.RegistryResponse_Code" json:"status,omitempty"`
	Message string                `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *RegistryResponse) Reset()                    { *m = RegistryResponse{} }
func (m *RegistryResponse) String() string            { return proto1.CompactTextString(m) }
func (*RegistryResponse) ProtoMessage()               {}
func (*RegistryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RegistryResponse) GetStatus() RegistryResponse_Code {
	if m != nil {
		return m.Status
	}
	return RegistryResponse_OK
}

func (m *RegistryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Service struct {
	Type           string   `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Host           string   `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Port           int32    `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	BusinessRoutes []string `protobuf:"bytes,4,rep,name=business_routes,json=businessRoutes" json:"business_routes,omitempty"`
	HealthRoute    string   `protobuf:"bytes,5,opt,name=health_route,json=healthRoute" json:"health_route,omitempty"`
	Signature      string   `protobuf:"bytes,6,opt,name=signature" json:"signature,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto1.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Service) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Service) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Service) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Service) GetBusinessRoutes() []string {
	if m != nil {
		return m.BusinessRoutes
	}
	return nil
}

func (m *Service) GetHealthRoute() string {
	if m != nil {
		return m.HealthRoute
	}
	return ""
}

func (m *Service) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type ServiceList struct {
	Services []*Service `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
}

func (m *ServiceList) Reset()                    { *m = ServiceList{} }
func (m *ServiceList) String() string            { return proto1.CompactTextString(m) }
func (*ServiceList) ProtoMessage()               {}
func (*ServiceList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ServiceList) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func init() {
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
	proto1.RegisterType((*ServiceType)(nil), "proto.ServiceType")
	proto1.RegisterType((*ServiceTypesList)(nil), "proto.ServiceTypesList")
	proto1.RegisterType((*RegistryResponse)(nil), "proto.RegistryResponse")
	proto1.RegisterType((*Service)(nil), "proto.Service")
	proto1.RegisterType((*ServiceList)(nil), "proto.ServiceList")
	proto1.RegisterEnum("proto.RegistryResponse_Code", RegistryResponse_Code_name, RegistryResponse_Code_value)
}

func init() { proto1.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0xae, 0x93, 0x50,
	0x10, 0xc6, 0xa5, 0xfc, 0x6b, 0x87, 0x1b, 0xee, 0xc9, 0xb8, 0x39, 0x8b, 0xbb, 0xe0, 0xb2, 0x91,
	0xb8, 0xe8, 0xe2, 0xea, 0xc6, 0xc4, 0x4d, 0xd3, 0x62, 0x42, 0xa4, 0xd4, 0x9c, 0xa2, 0x71, 0x65,
	0x43, 0xf5, 0xa4, 0x25, 0xb1, 0x85, 0x30, 0x07, 0x13, 0x9e, 0xca, 0x77, 0xf0, 0xc9, 0x0c, 0x07,
	0x5a, 0xab, 0x71, 0xc5, 0xcc, 0xf7, 0xfd, 0x18, 0x66, 0xf8, 0xc0, 0x3f, 0x49, 0xa2, 0xe2, 0x20,
	0x69, 0x5e, 0x37, 0x95, 0xaa, 0xd0, 0xd6, 0x8f, 0xd0, 0x05, 0x3b, 0x3e, 0xd5, 0xaa, 0x0b, 0x1f,
	0xc1, 0xdb, 0xca, 0xe6, 0x47, 0xf9, 0x55, 0xe6, 0x5d, 0x2d, 0x11, 0xc1, 0x52, 0x5d, 0x2d, 0xb9,
	0x11, 0x18, 0xd1, 0x4c, 0xe8, 0x3a, 0x7c, 0x0b, 0xec, 0x06, 0xa1, 0xb4, 0x24, 0x85, 0x11, 0xd8,
	0xbd, 0x47, 0xdc, 0x08, 0xcc, 0xc8, 0x7b, 0xc2, 0x61, 0xfa, 0xfc, 0x86, 0x13, 0x03, 0x10, 0xfe,
	0x32, 0x80, 0x09, 0x79, 0x28, 0x49, 0x35, 0x9d, 0x90, 0x54, 0x57, 0x67, 0x92, 0xf8, 0x1a, 0x1c,
	0x52, 0x85, 0x6a, 0x49, 0x7f, 0xc8, 0x7f, 0x7a, 0x18, 0xdf, 0xff, 0x17, 0x9c, 0x2f, 0xab, 0x6f,
	0x52, 0x8c, 0x2c, 0x72, 0x70, 0xc7, 0x6b, 0xf8, 0x44, 0xef, 0x77, 0x69, 0xc3, 0x2f, 0x60, 0xf5,
	0x24, 0x3a, 0x30, 0xd9, 0xbc, 0x67, 0xcf, 0xd0, 0x03, 0x37, 0xc9, 0x3e, 0x2d, 0xd2, 0x64, 0xc5,
	0x0c, 0x9c, 0x82, 0xf5, 0x6e, 0x91, 0xa4, 0x6c, 0x82, 0x77, 0x30, 0x5d, 0x2e, 0xb2, 0x65, 0x9c,
	0xc6, 0x2b, 0x66, 0xe2, 0x73, 0xb8, 0xcf, 0x36, 0xf9, 0x2e, 0x59, 0x7f, 0x48, 0xe3, 0x75, 0x9c,
	0xe5, 0xf1, 0x8a, 0x59, 0x3d, 0x9c, 0x7d, 0x4c, 0x53, 0x66, 0x23, 0x80, 0x13, 0x7f, 0x4e, 0xb6,
	0xf9, 0x96, 0x39, 0xe1, 0x4f, 0x03, 0xdc, 0xf1, 0xb6, 0xff, 0xfd, 0xa2, 0x5e, 0x3b, 0x56, 0xa4,
	0xc6, 0xb5, 0x74, 0xdd, 0x6b, 0x75, 0xd5, 0x28, 0x6e, 0x06, 0x46, 0x64, 0x0b, 0x5d, 0xe3, 0x0b,
	0xb8, 0xdf, 0xb7, 0x54, 0x9e, 0x25, 0xd1, 0xae, 0xa9, 0x5a, 0x25, 0x89, 0x5b, 0x81, 0x19, 0xcd,
	0x84, 0x7f, 0x91, 0x85, 0x56, 0xf1, 0x11, 0xee, 0x8e, 0xb2, 0xf8, 0xae, 0x8e, 0x03, 0xc6, 0x6d,
	0x3d, 0xd8, 0x1b, 0x34, 0xcd, 0xe0, 0x03, 0xcc, 0xa8, 0x3c, 0x9c, 0x0b, 0xd5, 0x36, 0x92, 0x3b,
	0xda, 0xff, 0x23, 0x84, 0x6f, 0xae, 0xb9, 0xea, 0xbc, 0x5e, 0xc2, 0x94, 0x86, 0xf6, 0x12, 0x99,
	0xff, 0x77, 0x64, 0xe2, 0xea, 0xef, 0x1d, 0x6d, 0xbc, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xc0,
	0x4c, 0x0c, 0x97, 0x3b, 0x02, 0x00, 0x00,
}
