// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry_messages.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegistryResponse_Code int32

const (
	RegistryResponse___DEFAULT       RegistryResponse_Code = 0
	RegistryResponse_OK              RegistryResponse_Code = 1
	RegistryResponse_INVALID         RegistryResponse_Code = 2
	RegistryResponse_FAIL            RegistryResponse_Code = 3
	RegistryResponse_CANCELED        RegistryResponse_Code = 4
	RegistryResponse_NOT_IMPLEMENTED RegistryResponse_Code = 5
	RegistryResponse_NULL            RegistryResponse_Code = 6
	RegistryResponse_EXISTS          RegistryResponse_Code = 7
)

var RegistryResponse_Code_name = map[int32]string{
	0: "__DEFAULT",
	1: "OK",
	2: "INVALID",
	3: "FAIL",
	4: "CANCELED",
	5: "NOT_IMPLEMENTED",
	6: "NULL",
	7: "EXISTS",
}
var RegistryResponse_Code_value = map[string]int32{
	"__DEFAULT":       0,
	"OK":              1,
	"INVALID":         2,
	"FAIL":            3,
	"CANCELED":        4,
	"NOT_IMPLEMENTED": 5,
	"NULL":            6,
	"EXISTS":          7,
}

func (x RegistryResponse_Code) String() string {
	return proto.EnumName(RegistryResponse_Code_name, int32(x))
}
func (RegistryResponse_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_registry_messages_892f23bf668c9492, []int{2, 0}
}

type ServiceType struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceType) Reset()         { *m = ServiceType{} }
func (m *ServiceType) String() string { return proto.CompactTextString(m) }
func (*ServiceType) ProtoMessage()    {}
func (*ServiceType) Descriptor() ([]byte, []int) {
	return fileDescriptor_registry_messages_892f23bf668c9492, []int{0}
}
func (m *ServiceType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceType.Unmarshal(m, b)
}
func (m *ServiceType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceType.Marshal(b, m, deterministic)
}
func (dst *ServiceType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceType.Merge(dst, src)
}
func (m *ServiceType) XXX_Size() int {
	return xxx_messageInfo_ServiceType.Size(m)
}
func (m *ServiceType) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceType.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceType proto.InternalMessageInfo

func (m *ServiceType) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type ServiceTypesList struct {
	Types                []*ServiceType `protobuf:"bytes,1,rep,name=types" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ServiceTypesList) Reset()         { *m = ServiceTypesList{} }
func (m *ServiceTypesList) String() string { return proto.CompactTextString(m) }
func (*ServiceTypesList) ProtoMessage()    {}
func (*ServiceTypesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_registry_messages_892f23bf668c9492, []int{1}
}
func (m *ServiceTypesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceTypesList.Unmarshal(m, b)
}
func (m *ServiceTypesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceTypesList.Marshal(b, m, deterministic)
}
func (dst *ServiceTypesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceTypesList.Merge(dst, src)
}
func (m *ServiceTypesList) XXX_Size() int {
	return xxx_messageInfo_ServiceTypesList.Size(m)
}
func (m *ServiceTypesList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceTypesList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceTypesList proto.InternalMessageInfo

func (m *ServiceTypesList) GetTypes() []*ServiceType {
	if m != nil {
		return m.Types
	}
	return nil
}

// RegistryResponse represents response from Registry service
// It contains status code and optional message
type RegistryResponse struct {
	Status               RegistryResponse_Code `protobuf:"varint,1,opt,name=status,enum=proto.RegistryResponse_Code" json:"status,omitempty"`
	Message              string                `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	ServiceIndex         uint32                `protobuf:"varint,3,opt,name=service_index,json=serviceIndex" json:"service_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RegistryResponse) Reset()         { *m = RegistryResponse{} }
func (m *RegistryResponse) String() string { return proto.CompactTextString(m) }
func (*RegistryResponse) ProtoMessage()    {}
func (*RegistryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_registry_messages_892f23bf668c9492, []int{2}
}
func (m *RegistryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistryResponse.Unmarshal(m, b)
}
func (m *RegistryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistryResponse.Marshal(b, m, deterministic)
}
func (dst *RegistryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistryResponse.Merge(dst, src)
}
func (m *RegistryResponse) XXX_Size() int {
	return xxx_messageInfo_RegistryResponse.Size(m)
}
func (m *RegistryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegistryResponse proto.InternalMessageInfo

func (m *RegistryResponse) GetStatus() RegistryResponse_Code {
	if m != nil {
		return m.Status
	}
	return RegistryResponse___DEFAULT
}

func (m *RegistryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegistryResponse) GetServiceIndex() uint32 {
	if m != nil {
		return m.ServiceIndex
	}
	return 0
}

type Service struct {
	Proto                string   `protobuf:"bytes,1,opt,name=proto" json:"proto,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Host                 string   `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	Health               string   `protobuf:"bytes,5,opt,name=health" json:"health,omitempty"`
	Weight               uint32   `protobuf:"varint,6,opt,name=weight" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_registry_messages_892f23bf668c9492, []int{3}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (dst *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(dst, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *Service) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Service) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Service) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Service) GetHealth() string {
	if m != nil {
		return m.Health
	}
	return ""
}

func (m *Service) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type ServiceList struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServiceList) Reset()         { *m = ServiceList{} }
func (m *ServiceList) String() string { return proto.CompactTextString(m) }
func (*ServiceList) ProtoMessage()    {}
func (*ServiceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_registry_messages_892f23bf668c9492, []int{4}
}
func (m *ServiceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceList.Unmarshal(m, b)
}
func (m *ServiceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceList.Marshal(b, m, deterministic)
}
func (dst *ServiceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceList.Merge(dst, src)
}
func (m *ServiceList) XXX_Size() int {
	return xxx_messageInfo_ServiceList.Size(m)
}
func (m *ServiceList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceList proto.InternalMessageInfo

func (m *ServiceList) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type ServiceInfo struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceInfo) Reset()         { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()    {}
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_registry_messages_892f23bf668c9492, []int{5}
}
func (m *ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfo.Unmarshal(m, b)
}
func (m *ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfo.Marshal(b, m, deterministic)
}
func (dst *ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfo.Merge(dst, src)
}
func (m *ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceInfo.Size(m)
}
func (m *ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfo proto.InternalMessageInfo

func (m *ServiceInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ServiceInfo) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type InstanceInfo struct {
	InstanceName         string   `protobuf:"bytes,1,opt,name=instanceName" json:"instanceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceInfo) Reset()         { *m = InstanceInfo{} }
func (m *InstanceInfo) String() string { return proto.CompactTextString(m) }
func (*InstanceInfo) ProtoMessage()    {}
func (*InstanceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_registry_messages_892f23bf668c9492, []int{6}
}
func (m *InstanceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceInfo.Unmarshal(m, b)
}
func (m *InstanceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceInfo.Marshal(b, m, deterministic)
}
func (dst *InstanceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceInfo.Merge(dst, src)
}
func (m *InstanceInfo) XXX_Size() int {
	return xxx_messageInfo_InstanceInfo.Size(m)
}
func (m *InstanceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceInfo proto.InternalMessageInfo

func (m *InstanceInfo) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceType)(nil), "proto.ServiceType")
	proto.RegisterType((*ServiceTypesList)(nil), "proto.ServiceTypesList")
	proto.RegisterType((*RegistryResponse)(nil), "proto.RegistryResponse")
	proto.RegisterType((*Service)(nil), "proto.Service")
	proto.RegisterType((*ServiceList)(nil), "proto.ServiceList")
	proto.RegisterType((*ServiceInfo)(nil), "proto.ServiceInfo")
	proto.RegisterType((*InstanceInfo)(nil), "proto.InstanceInfo")
	proto.RegisterEnum("proto.RegistryResponse_Code", RegistryResponse_Code_name, RegistryResponse_Code_value)
}

func init() {
	proto.RegisterFile("registry_messages.proto", fileDescriptor_registry_messages_892f23bf668c9492)
}

var fileDescriptor_registry_messages_892f23bf668c9492 = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x25, 0x69, 0x9a, 0xb6, 0xd3, 0x76, 0xb1, 0x06, 0x04, 0x39, 0x70, 0x28, 0xe6, 0x52, 0x71,
	0xe8, 0xa1, 0x20, 0x21, 0x24, 0x2e, 0x55, 0x9b, 0x95, 0x2c, 0xbc, 0x59, 0xe4, 0x66, 0x11, 0xb7,
	0x28, 0xb0, 0xa6, 0x8d, 0x44, 0x93, 0x28, 0x36, 0x1f, 0xfd, 0x0d, 0xfc, 0x5f, 0xce, 0xc8, 0x8e,
	0x1b, 0xb6, 0x68, 0x4f, 0x99, 0xf7, 0xfc, 0xe6, 0xeb, 0x4d, 0xe0, 0x69, 0x23, 0x77, 0x85, 0xd2,
	0xcd, 0x31, 0x3b, 0x48, 0xa5, 0xf2, 0x9d, 0x54, 0x8b, 0xba, 0xa9, 0x74, 0x85, 0x7d, 0xfb, 0xa1,
	0xcf, 0x61, 0xbc, 0x95, 0xcd, 0x8f, 0xe2, 0x8b, 0x4c, 0x8f, 0xb5, 0x44, 0x84, 0x40, 0x1f, 0x6b,
	0x19, 0x79, 0x33, 0x6f, 0x3e, 0x12, 0x36, 0xa6, 0xef, 0x80, 0xdc, 0x91, 0x28, 0x5e, 0x28, 0x8d,
	0x73, 0xe8, 0x9b, 0x37, 0x15, 0x79, 0xb3, 0xde, 0x7c, 0xbc, 0xc4, 0xb6, 0xe8, 0xe2, 0x8e, 0x4e,
	0xb4, 0x02, 0xfa, 0xc7, 0x03, 0x22, 0xdc, 0x0c, 0x42, 0xaa, 0xba, 0x2a, 0x95, 0xc4, 0xd7, 0x10,
	0x2a, 0x9d, 0xeb, 0xef, 0xca, 0x36, 0xba, 0x58, 0x3e, 0x73, 0xf9, 0xff, 0x0b, 0x17, 0xeb, 0xea,
	0x56, 0x0a, 0xa7, 0xc5, 0x08, 0x06, 0x6e, 0x89, 0xc8, 0xb7, 0xf3, 0x9d, 0x20, 0xbe, 0x80, 0xa9,
	0x6a, 0x5b, 0x67, 0x45, 0x79, 0x2b, 0x7f, 0x45, 0xbd, 0x99, 0x37, 0x9f, 0x8a, 0x89, 0x23, 0x99,
	0xe1, 0xe8, 0x01, 0x02, 0x53, 0x0e, 0xa7, 0x30, 0xca, 0xb2, 0x4d, 0x7c, 0xb9, 0xba, 0xe1, 0x29,
	0x79, 0x80, 0x21, 0xf8, 0xd7, 0xef, 0x89, 0x87, 0x63, 0x18, 0xb0, 0xe4, 0xe3, 0x8a, 0xb3, 0x0d,
	0xf1, 0x71, 0x08, 0xc1, 0xe5, 0x8a, 0x71, 0xd2, 0xc3, 0x09, 0x0c, 0xd7, 0xab, 0x64, 0x1d, 0xf3,
	0x78, 0x43, 0x02, 0x7c, 0x04, 0x0f, 0x93, 0xeb, 0x34, 0x63, 0x57, 0x1f, 0x78, 0x7c, 0x15, 0x27,
	0x69, 0xbc, 0x21, 0x7d, 0x23, 0x4e, 0x6e, 0x38, 0x27, 0x21, 0x02, 0x84, 0xf1, 0x27, 0xb6, 0x4d,
	0xb7, 0x64, 0x40, 0x7f, 0x7b, 0x30, 0x70, 0x7e, 0xe0, 0x63, 0x68, 0xed, 0x76, 0xbe, 0xb6, 0xa0,
	0x33, 0xdb, 0xff, 0x67, 0xb6, 0xe1, 0xf6, 0x95, 0xd2, 0x76, 0x81, 0x91, 0xb0, 0xb1, 0xe1, 0xea,
	0xaa, 0xd1, 0x51, 0x60, 0x97, 0xb2, 0x31, 0x3e, 0x81, 0x70, 0x2f, 0xf3, 0x6f, 0x7a, 0x1f, 0xf5,
	0xad, 0xd2, 0x21, 0xc3, 0xff, 0x94, 0xc5, 0x6e, 0xaf, 0xa3, 0xd0, 0xaa, 0x1d, 0xa2, 0x6f, 0xbb,
	0x3b, 0xdb, 0xfb, 0xbd, 0x84, 0xa1, 0xf3, 0xe6, 0x74, 0xc2, 0x8b, 0xf3, 0x13, 0x8a, 0xee, 0x9d,
	0xbe, 0xe9, 0x52, 0x59, 0xf9, 0xb5, 0xba, 0xef, 0x17, 0x31, 0xfb, 0xb5, 0xbe, 0xfb, 0xb6, 0x69,
	0x0b, 0xe8, 0x12, 0x26, 0xac, 0x54, 0x3a, 0x2f, 0x5d, 0x26, 0x85, 0x49, 0xe1, 0x70, 0x92, 0x1f,
	0x4e, 0x15, 0xce, 0xb8, 0xcf, 0xa1, 0x9d, 0xe2, 0xd5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x90,
	0x95, 0x01, 0x0c, 0xb8, 0x02, 0x00, 0x00,
}
