// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry_service.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RegistryService service

type RegistryServiceClient interface {
	GetHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Health, error)
	Register(ctx context.Context, in *Service, opts ...grpc.CallOption) (*RegistryResponse, error)
	ListServicesTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServiceTypesList, error)
	ListByType(ctx context.Context, in *ServiceType, opts ...grpc.CallOption) (*ServiceList, error)
	BestInstance(ctx context.Context, in *ServiceType, opts ...grpc.CallOption) (*Service, error)
	GetInfo(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*Service, error)
	GetInstanceInfo(ctx context.Context, in *InstanceInfo, opts ...grpc.CallOption) (*Service, error)
}

type registryServiceClient struct {
	cc *grpc.ClientConn
}

func NewRegistryServiceClient(cc *grpc.ClientConn) RegistryServiceClient {
	return &registryServiceClient{cc}
}

func (c *registryServiceClient) GetHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Health, error) {
	out := new(Health)
	err := grpc.Invoke(ctx, "/proto.RegistryService/GetHealth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) Register(ctx context.Context, in *Service, opts ...grpc.CallOption) (*RegistryResponse, error) {
	out := new(RegistryResponse)
	err := grpc.Invoke(ctx, "/proto.RegistryService/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) ListServicesTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServiceTypesList, error) {
	out := new(ServiceTypesList)
	err := grpc.Invoke(ctx, "/proto.RegistryService/ListServicesTypes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) ListByType(ctx context.Context, in *ServiceType, opts ...grpc.CallOption) (*ServiceList, error) {
	out := new(ServiceList)
	err := grpc.Invoke(ctx, "/proto.RegistryService/ListByType", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) BestInstance(ctx context.Context, in *ServiceType, opts ...grpc.CallOption) (*Service, error) {
	out := new(Service)
	err := grpc.Invoke(ctx, "/proto.RegistryService/BestInstance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetInfo(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*Service, error) {
	out := new(Service)
	err := grpc.Invoke(ctx, "/proto.RegistryService/GetInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetInstanceInfo(ctx context.Context, in *InstanceInfo, opts ...grpc.CallOption) (*Service, error) {
	out := new(Service)
	err := grpc.Invoke(ctx, "/proto.RegistryService/GetInstanceInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RegistryService service

type RegistryServiceServer interface {
	GetHealth(context.Context, *Empty) (*Health, error)
	Register(context.Context, *Service) (*RegistryResponse, error)
	ListServicesTypes(context.Context, *Empty) (*ServiceTypesList, error)
	ListByType(context.Context, *ServiceType) (*ServiceList, error)
	BestInstance(context.Context, *ServiceType) (*Service, error)
	GetInfo(context.Context, *ServiceInfo) (*Service, error)
	GetInstanceInfo(context.Context, *InstanceInfo) (*Service, error)
}

func RegisterRegistryServiceServer(s *grpc.Server, srv RegistryServiceServer) {
	s.RegisterService(&_RegistryService_serviceDesc, srv)
}

func _RegistryService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RegistryService/GetHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetHealth(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RegistryService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).Register(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_ListServicesTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).ListServicesTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RegistryService/ListServicesTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).ListServicesTypes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_ListByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).ListByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RegistryService/ListByType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).ListByType(ctx, req.(*ServiceType))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_BestInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).BestInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RegistryService/BestInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).BestInstance(ctx, req.(*ServiceType))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RegistryService/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetInfo(ctx, req.(*ServiceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetInstanceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetInstanceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RegistryService/GetInstanceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetInstanceInfo(ctx, req.(*InstanceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegistryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RegistryService",
	HandlerType: (*RegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _RegistryService_GetHealth_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _RegistryService_Register_Handler,
		},
		{
			MethodName: "ListServicesTypes",
			Handler:    _RegistryService_ListServicesTypes_Handler,
		},
		{
			MethodName: "ListByType",
			Handler:    _RegistryService_ListByType_Handler,
		},
		{
			MethodName: "BestInstance",
			Handler:    _RegistryService_BestInstance_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _RegistryService_GetInfo_Handler,
		},
		{
			MethodName: "GetInstanceInfo",
			Handler:    _RegistryService_GetInstanceInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry_service.proto",
}

func init() { proto1.RegisterFile("registry_service.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xd0, 0xdd, 0x4a, 0x02, 0x41,
	0x14, 0x07, 0x70, 0x0a, 0xec, 0x63, 0x30, 0xcd, 0x13, 0x68, 0x2d, 0x52, 0xb2, 0x91, 0x48, 0x81,
	0x03, 0x75, 0xd7, 0xa5, 0x10, 0x26, 0x44, 0x90, 0x75, 0x57, 0x61, 0xa3, 0x9d, 0xd6, 0x01, 0x9d,
	0x59, 0x76, 0x86, 0x68, 0x91, 0xbd, 0x09, 0x7a, 0x82, 0x1e, 0xad, 0x57, 0xe8, 0x41, 0x62, 0x67,
	0x46, 0xaa, 0xdd, 0x3e, 0xae, 0x86, 0x19, 0xcf, 0xff, 0xf7, 0x3f, 0x2e, 0xa9, 0x46, 0x18, 0x70,
	0xa5, 0xa3, 0x78, 0xa0, 0x30, 0x7a, 0xe4, 0x23, 0x6c, 0x87, 0x91, 0xd4, 0x12, 0x0a, 0xe6, 0xf0,
	0xea, 0x81, 0x94, 0xc1, 0x04, 0x29, 0x0b, 0x39, 0x65, 0x42, 0x48, 0xcd, 0x34, 0x97, 0x42, 0xd9,
	0x21, 0xaf, 0x34, 0x45, 0xa5, 0x58, 0x80, 0xee, 0x7e, 0xf8, 0x52, 0x20, 0xe5, 0xbe, 0xf3, 0x2e,
	0x2d, 0x07, 0x1d, 0xb2, 0xda, 0x45, 0x7d, 0x8a, 0x6c, 0xa2, 0xc7, 0x50, 0xb4, 0x83, 0xed, 0x93,
	0x69, 0xa8, 0x63, 0x6f, 0xcd, 0xdd, 0xec, 0x8f, 0xfe, 0xe6, 0xf3, 0xdb, 0xfb, 0xeb, 0x22, 0xc0,
	0x3a, 0x9d, 0xef, 0x44, 0xc7, 0x36, 0x76, 0x41, 0x56, 0x2c, 0x8b, 0x11, 0x94, 0x5c, 0xc8, 0xf9,
	0x5e, 0xcd, 0xdd, 0xe7, 0xbd, 0x7d, 0x54, 0xa1, 0x14, 0x0a, 0xfd, 0xba, 0xe1, 0xaa, 0x7e, 0xe5,
	0x93, 0x73, 0x7f, 0xf1, 0x78, 0x61, 0x1f, 0xae, 0x49, 0xe5, 0x8c, 0x2b, 0xed, 0x14, 0x75, 0x15,
	0x87, 0xa8, 0x32, 0xeb, 0xd5, 0xbe, 0x37, 0x99, 0x91, 0x34, 0xe3, 0xef, 0x18, 0x79, 0x0b, 0x6a,
	0x39, 0x99, 0x6a, 0xe3, 0xdc, 0x10, 0x92, 0x0e, 0x76, 0xe2, 0x34, 0x03, 0x90, 0x77, 0xbc, 0xcc,
	0x9b, 0x61, 0x9b, 0x86, 0x6d, 0xc0, 0xf6, 0x2f, 0x2c, 0x9d, 0xa5, 0x47, 0x02, 0x03, 0x52, 0xec,
	0xa0, 0xd2, 0x3d, 0xa1, 0x34, 0x13, 0xa3, 0x9f, 0xfd, 0xcc, 0x57, 0xf2, 0x0f, 0x8c, 0xbd, 0x07,
	0xbb, 0x7f, 0xdb, 0x74, 0x88, 0x4a, 0xc3, 0x2d, 0x59, 0xee, 0xa2, 0xee, 0x89, 0x07, 0x99, 0xb5,
	0xd3, 0xb7, 0x9c, 0xdd, 0x36, 0x76, 0x0b, 0x9a, 0xff, 0xd8, 0x33, 0x2e, 0xee, 0xf1, 0x29, 0x81,
	0x3b, 0x52, 0x36, 0xbc, 0x5d, 0xdf, 0xd4, 0x6c, 0x38, 0xf2, 0xeb, 0x63, 0xae, 0xa7, 0x65, 0x7a,
	0x7c, 0x68, 0xe4, 0x7b, 0x66, 0xdc, 0x05, 0xcf, 0xd9, 0x14, 0x93, 0xe1, 0x92, 0x09, 0x1e, 0x7d,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x7f, 0xa6, 0x65, 0xdd, 0x02, 0x00, 0x00,
}
