// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry_service.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegistryServiceClient is the client API for RegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistryServiceClient interface {
	GetHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Health, error)
	Register(ctx context.Context, in *Service, opts ...grpc.CallOption) (*RegistryResponse, error)
	ListServicesTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServiceTypesList, error)
	ListByType(ctx context.Context, in *ServiceType, opts ...grpc.CallOption) (*ServiceList, error)
	BestInstance(ctx context.Context, in *ServiceType, opts ...grpc.CallOption) (*Service, error)
	GetInfo(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*Service, error)
	GetInstanceInfo(ctx context.Context, in *InstanceInfo, opts ...grpc.CallOption) (*Service, error)
}

type registryServiceClient struct {
	cc *grpc.ClientConn
}

func NewRegistryServiceClient(cc *grpc.ClientConn) RegistryServiceClient {
	return &registryServiceClient{cc}
}

func (c *registryServiceClient) GetHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Health, error) {
	out := new(Health)
	err := c.cc.Invoke(ctx, "/proto.RegistryService/GetHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) Register(ctx context.Context, in *Service, opts ...grpc.CallOption) (*RegistryResponse, error) {
	out := new(RegistryResponse)
	err := c.cc.Invoke(ctx, "/proto.RegistryService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) ListServicesTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServiceTypesList, error) {
	out := new(ServiceTypesList)
	err := c.cc.Invoke(ctx, "/proto.RegistryService/ListServicesTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) ListByType(ctx context.Context, in *ServiceType, opts ...grpc.CallOption) (*ServiceList, error) {
	out := new(ServiceList)
	err := c.cc.Invoke(ctx, "/proto.RegistryService/ListByType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) BestInstance(ctx context.Context, in *ServiceType, opts ...grpc.CallOption) (*Service, error) {
	out := new(Service)
	err := c.cc.Invoke(ctx, "/proto.RegistryService/BestInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetInfo(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*Service, error) {
	out := new(Service)
	err := c.cc.Invoke(ctx, "/proto.RegistryService/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetInstanceInfo(ctx context.Context, in *InstanceInfo, opts ...grpc.CallOption) (*Service, error) {
	out := new(Service)
	err := c.cc.Invoke(ctx, "/proto.RegistryService/GetInstanceInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServiceServer is the server API for RegistryService service.
type RegistryServiceServer interface {
	GetHealth(context.Context, *Empty) (*Health, error)
	Register(context.Context, *Service) (*RegistryResponse, error)
	ListServicesTypes(context.Context, *Empty) (*ServiceTypesList, error)
	ListByType(context.Context, *ServiceType) (*ServiceList, error)
	BestInstance(context.Context, *ServiceType) (*Service, error)
	GetInfo(context.Context, *ServiceInfo) (*Service, error)
	GetInstanceInfo(context.Context, *InstanceInfo) (*Service, error)
}

func RegisterRegistryServiceServer(s *grpc.Server, srv RegistryServiceServer) {
	s.RegisterService(&_RegistryService_serviceDesc, srv)
}

func _RegistryService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RegistryService/GetHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetHealth(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RegistryService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).Register(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_ListServicesTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).ListServicesTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RegistryService/ListServicesTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).ListServicesTypes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_ListByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).ListByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RegistryService/ListByType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).ListByType(ctx, req.(*ServiceType))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_BestInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).BestInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RegistryService/BestInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).BestInstance(ctx, req.(*ServiceType))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RegistryService/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetInfo(ctx, req.(*ServiceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetInstanceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetInstanceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RegistryService/GetInstanceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetInstanceInfo(ctx, req.(*InstanceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegistryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RegistryService",
	HandlerType: (*RegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _RegistryService_GetHealth_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _RegistryService_Register_Handler,
		},
		{
			MethodName: "ListServicesTypes",
			Handler:    _RegistryService_ListServicesTypes_Handler,
		},
		{
			MethodName: "ListByType",
			Handler:    _RegistryService_ListByType_Handler,
		},
		{
			MethodName: "BestInstance",
			Handler:    _RegistryService_BestInstance_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _RegistryService_GetInfo_Handler,
		},
		{
			MethodName: "GetInstanceInfo",
			Handler:    _RegistryService_GetInstanceInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry_service.proto",
}

func init() {
	proto.RegisterFile("registry_service.proto", fileDescriptor_registry_service_54f7b60a09f758ba)
}

var fileDescriptor_registry_service_54f7b60a09f758ba = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xd0, 0xdd, 0x4a, 0xf3, 0x30,
	0x18, 0x07, 0x70, 0xde, 0x17, 0xe6, 0x47, 0xd8, 0x9c, 0x7b, 0x84, 0x55, 0xcb, 0xd0, 0x51, 0x71,
	0x0c, 0x85, 0x05, 0xf4, 0xcc, 0xc3, 0x81, 0xcc, 0x81, 0x08, 0x4e, 0xcf, 0x54, 0x66, 0x36, 0x1f,
	0xbb, 0xc0, 0x96, 0x94, 0x26, 0x88, 0x65, 0xec, 0x44, 0xf0, 0x0a, 0xbc, 0x34, 0x6f, 0xc1, 0x0b,
	0x91, 0x26, 0x99, 0x1f, 0xad, 0x1f, 0x47, 0x21, 0xc9, 0xf3, 0xff, 0xfd, 0xd3, 0x92, 0x6a, 0x8c,
	0x21, 0x57, 0x3a, 0x4e, 0xfa, 0x0a, 0xe3, 0x7b, 0x3e, 0xc4, 0x56, 0x14, 0x4b, 0x2d, 0xa1, 0x60,
	0x16, 0xbf, 0x16, 0x4a, 0x19, 0x8e, 0x91, 0xb2, 0x88, 0x53, 0x26, 0x84, 0xd4, 0x4c, 0x73, 0x29,
	0x94, 0x1d, 0xf2, 0xbd, 0xf7, 0xf0, 0x04, 0x95, 0x62, 0x21, 0xce, 0x2f, 0x4a, 0x21, 0x0a, 0x8c,
	0xd9, 0xd8, 0x6e, 0xf7, 0x9f, 0x0a, 0xa4, 0xdc, 0x73, 0xa3, 0xe7, 0xb6, 0x06, 0xda, 0x64, 0xb9,
	0x83, 0xfa, 0x18, 0xd9, 0x58, 0x8f, 0xa0, 0x68, 0x07, 0x5b, 0x47, 0x93, 0x48, 0x27, 0x7e, 0xc9,
	0xed, 0xec, 0x65, 0xb0, 0xfe, 0xf8, 0xf2, 0xfa, 0xfc, 0x1f, 0x60, 0x95, 0xce, 0xeb, 0xe8, 0xc8,
	0xc6, 0xce, 0xc8, 0x92, 0x65, 0x31, 0x86, 0x15, 0x17, 0x72, 0xbe, 0xef, 0xb9, 0xfd, 0xbc, 0xb7,
	0x87, 0x2a, 0x92, 0x42, 0x61, 0x50, 0x33, 0x5c, 0x35, 0xa8, 0x7c, 0x70, 0xee, 0xd3, 0x0f, 0xff,
	0xed, 0xc2, 0x25, 0xa9, 0x9c, 0x70, 0xa5, 0x9d, 0xa2, 0x2e, 0x92, 0x08, 0x55, 0xe6, 0x79, 0xde,
	0xd7, 0x26, 0x33, 0x92, 0x66, 0x82, 0x2d, 0x23, 0x6f, 0x80, 0x97, 0x93, 0xa9, 0x36, 0xce, 0x15,
	0x21, 0xe9, 0x60, 0x3b, 0x49, 0x33, 0x00, 0x79, 0xc7, 0xcf, 0x9c, 0x19, 0xb6, 0x61, 0xd8, 0x3a,
	0x6c, 0xfe, 0xc0, 0xd2, 0x69, 0xba, 0xcc, 0xa0, 0x4f, 0x8a, 0x6d, 0x54, 0xba, 0x2b, 0x94, 0x66,
	0x62, 0xf8, 0xbd, 0x9f, 0xf9, 0x4b, 0xc1, 0x9e, 0xb1, 0x77, 0x60, 0xfb, 0x77, 0x9b, 0x0e, 0x50,
	0x69, 0xb8, 0x26, 0x8b, 0x1d, 0xd4, 0x5d, 0x71, 0x27, 0xb3, 0x76, 0x7a, 0x96, 0xb3, 0x5b, 0xc6,
	0x6e, 0x42, 0xe3, 0x0f, 0x7b, 0xca, 0xc5, 0x2d, 0x3e, 0xcc, 0xe0, 0x86, 0x94, 0x0d, 0x6f, 0x9f,
	0x6f, 0x6a, 0xd6, 0x1c, 0xf9, 0xf9, 0x30, 0xd7, 0xd3, 0x34, 0x3d, 0x01, 0xd4, 0xf3, 0x3d, 0x53,
	0xee, 0x82, 0xa7, 0x6c, 0x82, 0xb3, 0xc1, 0x82, 0x09, 0x1e, 0xbc, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xcc, 0x83, 0xe5, 0x9c, 0xf5, 0x02, 0x00, 0x00,
}
